apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: example01
spec:
  type: ClusterIP
  selector:
    app: trivial-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
