---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: example02
  annotations:
    creation: at-{{ now | date "20160102150405" }}
spec:
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
        ports:
        - containerPort: 8080
